//! Procedural macros for [`conduit-worker`].
//!
//! Currently exposes one attribute: [`macro@handler`]. Apply it to a free
//! `async fn` to generate a unit struct + `impl Handler` that delegates to
//! that function.
//!
//! ```ignore
//! use conduit_worker::{ExternalTask, HandlerError, HandlerResult, handler};
//!
//! #[handler(topic = "http.call")]
//! async fn http_call(_task: &ExternalTask) -> Result<HandlerResult, HandlerError> {
//!     Ok(HandlerResult::ok())
//! }
//!
//! // Use the generated struct:
//! //   Runner::new(client, std::sync::Arc::new(HttpCallHandler), config);
//! ```

use proc_macro::TokenStream;
use proc_macro2::Span;
use quote::quote;
use syn::{
    parse::{Parse, ParseStream},
    parse_macro_input, Ident, ItemFn, LitStr, Token,
};

/// `topic = "..."` argument to the attribute.
struct HandlerArgs {
    topic: LitStr,
}

impl Parse for HandlerArgs {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let key: Ident = input.parse()?;
        if key != "topic" {
            return Err(syn::Error::new(
                key.span(),
                "expected `topic = \"...\"`",
            ));
        }
        let _: Token![=] = input.parse()?;
        let topic: LitStr = input.parse()?;
        Ok(Self { topic })
    }
}

/// Convert a snake_case identifier to PascalCase.
fn pascal_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut upper = true;
    for c in s.chars() {
        if c == '_' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// Attribute macro that turns an `async fn handler(task: &ExternalTask) -> Result<HandlerResult, HandlerError>`
/// into a unit struct that implements [`conduit_worker::Handler`].
///
/// The struct's name is the function name converted to PascalCase plus
/// the suffix `Handler`. For example, `async fn http_call(...)` produces
/// `pub struct HttpCallHandler;` and an `impl Handler for HttpCallHandler`
/// whose `topic()` returns the literal you passed.
///
/// Use it like:
///
/// ```ignore
/// #[handler(topic = "http.call")]
/// async fn http_call(task: &ExternalTask) -> Result<HandlerResult, HandlerError> {
///     // ...
/// }
///
/// let runner = Runner::new(client, Arc::new(HttpCallHandler), RunnerConfig::new("w-1"));
/// ```
#[proc_macro_attribute]
pub fn handler(args: TokenStream, input: TokenStream) -> TokenStream {
    let args = parse_macro_input!(args as HandlerArgs);
    let func = parse_macro_input!(input as ItemFn);

    if func.sig.asyncness.is_none() {
        return syn::Error::new_spanned(
            &func.sig.fn_token,
            "#[handler] requires an `async fn`",
        )
        .to_compile_error()
        .into();
    }

    let fn_ident = &func.sig.ident;
    let struct_name = format!("{}Handler", pascal_case(&fn_ident.to_string()));
    let struct_ident = Ident::new(&struct_name, Span::call_site());
    let topic = &args.topic;
    let vis = &func.vis;

    let expanded = quote! {
        #func

        #[doc = concat!("Generated by `#[handler]` from `", stringify!(#fn_ident), "`.")]
        #vis struct #struct_ident;

        #[::conduit_worker::__macro_support::async_trait]
        impl ::conduit_worker::Handler for #struct_ident {
            fn topic(&self) -> &str {
                #topic
            }

            async fn handle(
                &self,
                task: &::conduit_worker::ExternalTask,
            ) -> ::core::result::Result<
                ::conduit_worker::HandlerResult,
                ::conduit_worker::HandlerError,
            > {
                #fn_ident(task).await
            }
        }
    };

    expanded.into()
}
